### ISSUE TITLE
When will there be releases?

### ISSUE THREAD

**Issue by WeeSee** [adfinis-sygroup/document-merge-service#177]
When do you plan to create releases? 

Can I already start to use this repo or is it still under heavy development and long before version 1.0.0?

**Comment by open-dynaMIX** [comment]
Hey @WeeSee!

We're discussing how we want to handle releases. We use this project in production already, so it's also in our own interest to track changes.

**Comment by open-dynaMIX** [comment]
The first release is [available](https://github.com/adfinis-sygroup/document-merge-service/releases/tag/v0.0.1).

Just a heads up: We're about to release v1.0.0 after #178 is merged. So maybe you want to wait for that.
