### ISSUE TITLE
Missing docs and examples - even in new Version 3

### ISSUE THREAD

**Issue by WeeSee** [adfinis-sygroup/document-merge-service#223]
Where are docs to this great service?
There is a test directory but no examples which we could learn from.

What I'd like to have:

* How create docx templates
* Which placeholders are allowed?
* What are limitations of the templating feature?
* Samples, samples, samples (docx-templates, csv merge data, result documents in pdf format)
* The most simple usage pattern

**Comment by open-dynaMIX** [comment]
Hey @WeeSee 

I'm very sorry, for the late reply!

Back in March, we added some docs about [configuration](https://github.com/adfinis-sygroup/document-merge-service/blob/master/CONFIGURATION.md) and [usage](https://github.com/adfinis-sygroup/document-merge-service/blob/master/USAGE.md).

If you feel something important is still missing or want to further improve the docs, feel free to reopen this issue and/or open a pull request.
