### ISSUE TITLE
Add date filter

### ISSUE THREAD

**Issue by czosel** [adfinis-sygroup/document-merge-service#88]
In order to make date formatting in documents more powerful / flexible, adding a date filter would be nice. Maybe something like
```jinja
{{ my_date | date("%d.%m.%Y") }}
```
Not sure if a separate `datetime` filter would be needed, probably `date` could also support printing the "time" part.

**Comment by czosel** [comment]
Important: We need to consider how/if this would be localized.

**Comment by open-dynaMIX** [comment]
Nice!

Here an extended version with support for datetime, date and time:

```python
import jinja2
from datetime import datetime


def datetimeformat(value, in_format='%Y-%m-%d', out_format='%d.%m.%Y'):
    if value is None:
        return ""
    else:
        return datetime.strptime(value, in_format).strftime(out_format)


jinja_env = jinja2.Environment()
jinja_env.filters['datetimeformat'] = datetimeformat
```

**Comment by fkm** [comment]
Good idea :smiley:
